### ISSUE TITLE
Github page does not render the latex of the markdown

### ISSUE THREAD

**Issue by neandertha1er** [primitivefinance/rmms-py#2]
Hey, this is not really a problem with the work, it's more of a usability suggestion.

The `Primitive RMM-01` whitepaper references this work multiple times as `[e21]`. 
It seems fundamental to get a grip on modelling errors.
I could however not find it in readable form using google search and my brain does not parse latex :)

Maybe you want to attach a pdf / html / whatever version?

I attached my (slightly shitty) one in case you want to use it until you have something better ...

[Simulating RMMS - Documentation.pdf](https://github.com/primitivefinance/rmms-py/files/7699358/Simulating.RMMS.-.Documentation.pdf)

**Comment by kinrezC** [comment]
This is awesome!  Would you like to make the PR to add it?
